drop table Transshipments
drop table PackageTransport
drop table Transports
drop table Driverlogs
drop table Vehicles
drop table Deliverymen
drop table Delivery_units
drop table Tracker
drop table Tracking_info
drop table Packages
drop table Orders
drop table Receivers
drop table HasAddress
drop table Addresses
drop table Users
